name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Decrypt the certificate
      run: |
        echo "$CERTIFICATE_P12" | base64 --decode > certificate.p12

    - name: Install the certificate
      run: |
          security create-keychain -p "" build.keychain
          security import certificate.p12 -t agg -k ~/Library/Keychains/build.keychain -P "$CERTIFICATE_PASSWORD" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
      env:
          CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

    - name: Set up provisioning profile
      run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
      env:
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Run build
      run: xcodebuild -allowProvisioningUpdates


  
